# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/emotet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/emotet.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15protobuf/emotet.proto\"\x8b\x01\n\x08HostInfo\x12\x11\n\tscmanager\x18\x01 \x02(\x05\x12\x0e\n\x06\x62ot_id\x18\x02 \x02(\t\x12\x0c\n\x04\x61rch\x18\x03 \x02(\x05\x12\x12\n\nsession_id\x18\x04 \x02(\x05\x12\x12\n\nfile_crc32\x18\x05 \x02(\x07\x12\x15\n\rproccess_list\x18\x06 \x02(\t\x12\x0f\n\x07unknown\x18\x07 \x02(\t\"*\n\tC2Request\x12\x0f\n\x07\x63ommand\x18\x01 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\";\n\nC2Response\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x0c\n\x04\x66ile\x18\x02 \x01(\x0c\x12\x0f\n\x07modules\x18\x03 \x01(\x0c\"2\n\x06Module\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HOSTINFO = _descriptor.Descriptor(
  name='HostInfo',
  full_name='HostInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scmanager', full_name='HostInfo.scmanager', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bot_id', full_name='HostInfo.bot_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arch', full_name='HostInfo.arch', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='HostInfo.session_id', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_crc32', full_name='HostInfo.file_crc32', index=4,
      number=5, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proccess_list', full_name='HostInfo.proccess_list', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown', full_name='HostInfo.unknown', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=165,
)


_C2REQUEST = _descriptor.Descriptor(
  name='C2Request',
  full_name='C2Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='C2Request.command', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='C2Request.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=209,
)


_C2RESPONSE = _descriptor.Descriptor(
  name='C2Response',
  full_name='C2Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='C2Response.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file', full_name='C2Response.file', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modules', full_name='C2Response.modules', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=270,
)


_MODULE = _descriptor.Descriptor(
  name='Module',
  full_name='Module',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Module.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='Module.action', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='Module.data', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=322,
)

DESCRIPTOR.message_types_by_name['HostInfo'] = _HOSTINFO
DESCRIPTOR.message_types_by_name['C2Request'] = _C2REQUEST
DESCRIPTOR.message_types_by_name['C2Response'] = _C2RESPONSE
DESCRIPTOR.message_types_by_name['Module'] = _MODULE

HostInfo = _reflection.GeneratedProtocolMessageType('HostInfo', (_message.Message,), dict(
  DESCRIPTOR = _HOSTINFO,
  __module__ = 'protobuf.emotet_pb2'
  # @@protoc_insertion_point(class_scope:HostInfo)
  ))
_sym_db.RegisterMessage(HostInfo)

C2Request = _reflection.GeneratedProtocolMessageType('C2Request', (_message.Message,), dict(
  DESCRIPTOR = _C2REQUEST,
  __module__ = 'protobuf.emotet_pb2'
  # @@protoc_insertion_point(class_scope:C2Request)
  ))
_sym_db.RegisterMessage(C2Request)

C2Response = _reflection.GeneratedProtocolMessageType('C2Response', (_message.Message,), dict(
  DESCRIPTOR = _C2RESPONSE,
  __module__ = 'protobuf.emotet_pb2'
  # @@protoc_insertion_point(class_scope:C2Response)
  ))
_sym_db.RegisterMessage(C2Response)

Module = _reflection.GeneratedProtocolMessageType('Module', (_message.Message,), dict(
  DESCRIPTOR = _MODULE,
  __module__ = 'protobuf.emotet_pb2'
  # @@protoc_insertion_point(class_scope:Module)
  ))
_sym_db.RegisterMessage(Module)


# @@protoc_insertion_point(module_scope)
